// Tag canonicalization. The seed pool was generated by an LLM and carries
// drift: easy-going / easygoing, settled / settled in Berlin, exploratory /
// explorative, etc. Deterministic matching compares tag strings directly, so
// un-canonicalized drift scores as zero overlap and the demo looks worse than
// it is. We canonicalize on read (both the requester's chip picks and the seed
// candidates) so they meet in one vocabulary.
//
// Slice 5 will replay the seed users through this same map so the stored tags
// are canonical at rest; until then this runtime pass covers it.

// Lowercased, trimmed → canonical form. Keys are the drift variants we've
// observed in the seed pool (see the DB audit in PROJECT.md change log).
const DRIFT: Record<string, string> = {
  // personality / vibe
  "easy-going": "easygoing",
  "chilled": "chill",
  "exploratory": "explorative",
  "explorer": "explorative",
  "laid back": "laid-back",
  // life context
  "settled in berlin": "settled",
  "settled expat": "settled",
  "long-time berliner": "long-time",
  "long-time resident": "long-time",
  "long-time berlin": "long-time",
  "long time": "long-time",
  // activities (collapse plural / venue-suffix drift toward a shared root)
  "techno clubs": "techno club",
  "clubbing": "techno club",
  "gallery openings": "gallery",
  "art openings": "gallery",
  "art opening": "gallery",
  "art exhibits": "gallery",
  "art exhibit": "gallery",
  "yoga studios": "yoga",
  "dinner parties": "dinner party",
  "intentional dinners": "dinner party",
  "indie cinema": "indie film",
  "indie film": "indie film",
  // interests
  "arts": "art",
  "contemporary art": "art",
  "literature": "books",
  "vinyl hunting": "vinyl",
};

export function canon(tag: string): string {
  const t = tag.trim().toLowerCase();
  return DRIFT[t] ?? t;
}

// Canonicalize an array, dropping empties and de-duplicating.
export function canonAll(tags: string[] | undefined | null): string[] {
  if (!tags) return [];
  const out: string[] = [];
  const seen = new Set<string>();
  for (const raw of tags) {
    if (!raw) continue;
    const c = canon(raw);
    if (!c || seen.has(c)) continue;
    seen.add(c);
    out.push(c);
  }
  return out;
}

// Weighted Jaccard over two canonical tag sets. |A ∩ B| / |A ∪ B|, in [0,1].
// Empty-vs-empty is 0 (no signal), not 1.
export function jaccard(a: string[], b: string[]): number {
  if (a.length === 0 || b.length === 0) return 0;
  const setA = new Set(a);
  const setB = new Set(b);
  let inter = 0;
  for (const x of setA) if (setB.has(x)) inter++;
  const union = setA.size + setB.size - inter;
  return union === 0 ? 0 : inter / union;
}

// Returns the canonical tags shared by both arrays.
// Useful for generating explanation copy: "Both into startups, techno".
export function commonTags(a: string[], b: string[]): string[] {
  const ca = canonAll(a);
  const cb = new Set(canonAll(b));
  return ca.filter((tag) => cb.has(tag));
}

// True if the two canonical sets share at least one member.
export function overlaps(a: string[], b: string[]): boolean {
  if (a.length === 0 || b.length === 0) return false;
  const setB = new Set(b);
  return a.some((x) => setB.has(x));
}
